FROM alpine:3.20
EXPOSE 8080

ARG APPNAME=AQMFluxAPI

ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_USER=timescale
# ENV DB_PASSWORD=timescale
ENV DB_NAME=aqmflux

ENV MQTT_HOST=localhost
ENV MQTT_PORT=1883
ENV MQTT_USER=admin
# ENV MQTT_PASSWORD=admin

ENV NTFY_HOST=http://localhost
# ENV NTFY_TOKEN=ntfy_token

ENV API_ORIGINS=http://localhost:5173
ENV API_METHODS=GET,\ POST,\ PUT,\ DELETE,\ OPTIONS,\ HEAD
ENV API_AUTHORIZATION_DURATION=60
ENV API_REFRESH_DURATION=1440

ENV HOST=localhost
ENV PORT=8080
ENV SERVE_HTML=true

COPY ./build/${APPNAME} /AQMFluxAPI
RUN apk add --no-cache libc6-compat
CMD ["./AQMFluxAPI"]