// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"database/sql"
	"time"
)

type Attribute struct {
	AttributeID   int32  `json:"attribute_id"`
	AttributeName string `json:"attribute_name"`
	AttributeDesc string `json:"attribute_desc"`
	AttributeUnit string `json:"attribute_unit"`
}

type Config struct {
	Ckey   string         `json:"ckey"`
	Cvalue sql.NullString `json:"cvalue"`
	Ctype  int32          `json:"ctype"`
}

type Device struct {
	DeviceID   int32  `json:"device_id"`
	DeviceName string `json:"device_name"`
	LocationID int32  `json:"location_id"`
	DeviceDesc string `json:"device_desc"`
}

type Deviceaddr struct {
	DeviceID int32  `json:"device_id"`
	IpAddr   string `json:"ip_addr"`
	MacAddr  string `json:"mac_addr"`
	Port     int32  `json:"port"`
}

type Devicelocation struct {
	LocationID   int32  `json:"location_id"`
	LocationName string `json:"location_name"`
	LocationDesc string `json:"location_desc"`
}

type Devicestate struct {
	DeviceID     int32 `json:"device_id"`
	Isrestarting bool  `json:"isrestarting"`
	Isrunning    bool  `json:"isrunning"`
	Isupdating   bool  `json:"isupdating"`
}

type Measurement struct {
	Mtime       time.Time `json:"mtime"`
	SensorID    int32     `json:"sensor_id"`
	DeviceID    int32     `json:"device_id"`
	AttributeID int32     `json:"attribute_id"`
	Mvalue      float64   `json:"mvalue"`
}

type Notificationmessage struct {
	ID              int32          `json:"id"`
	Title           string         `json:"title"`
	Topic           string         `json:"topic"`
	Payload         string         `json:"payload"`
	Tags            sql.NullString `json:"tags"`
	Messagepriority int32          `json:"messagepriority"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Operator struct {
	ID        int32  `json:"id"`
	Op        string `json:"op"`
	Variables int32  `json:"variables"`
}

type Reminder struct {
	ID              int32        `json:"id"`
	MessageID       int32        `json:"message_id"`
	Frequency       int32        `json:"frequency"`
	Remindername    string       `json:"remindername"`
	Reminderenabled bool         `json:"reminderenabled"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	LastReminded    sql.NullTime `json:"last_reminded"`
}

type Remindersdevice struct {
	ID       int32  `json:"id"`
	DeviceID int32  `json:"device_id"`
	Rname    string `json:"rname"`
}

type Secret struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Value     string       `json:"value"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Sensor struct {
	SensorID   int32  `json:"sensor_id"`
	SensorName string `json:"sensor_name"`
	SensorDesc string `json:"sensor_desc"`
}

type Sensordevice struct {
	SensorID int32 `json:"sensor_id"`
	DeviceID int32 `json:"device_id"`
}

type Threshold struct {
	ID             int32           `json:"id"`
	SensorID       int32           `json:"sensor_id"`
	DeviceID       int32           `json:"device_id"`
	AttributeID    int32           `json:"attribute_id"`
	MessageID      int32           `json:"message_id"`
	Value1         float64         `json:"value1"`
	Value2         sql.NullFloat64 `json:"value2"`
	Frequency      int32           `json:"frequency"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	LastTriggered  sql.NullTime    `json:"last_triggered"`
	OperatorID     int32           `json:"operator_id"`
	Triggername    string          `json:"triggername"`
	Triggerenabled bool            `json:"triggerenabled"`
}
