// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operators.sql

package repo

import (
	"context"
)

const getOperators = `-- name: GetOperators :many
SELECT id, op, variables FROM Operator
`

func (q *Queries) GetOperators(ctx context.Context) ([]Operator, error) {
	rows, err := q.query(ctx, q.getOperatorsStmt, getOperators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operator{}
	for rows.Next() {
		var i Operator
		if err := rows.Scan(&i.ID, &i.Op, &i.Variables); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
