DROP TABLE IF EXISTS Threshold;
DROP TABLE IF EXISTS RemindersDevice;
DROP TABLE IF EXISTS Reminders;
DROP TABLE IF EXISTS NotificationMessage;
DROP TABLE IF EXISTS Operator;

DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS Attribute;
DROP TABLE IF EXISTS Sensor;
DROP TABLE IF EXISTS DeviceAddr;
DROP TABLE IF EXISTS DeviceState;
DROP TABLE IF EXISTS Device;
DROP TABLE IF EXISTS DeviceLocation;

DROP TABLE IF EXISTS Config;